CREATE TABLE IF NOT EXISTS EmpresasNuevas (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK del registro temporal',
    Estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_APROBACION' COMMENT 'Estado actual del proceso',
    EstadoDetalle VARCHAR(255) NULL COMMENT 'Detalle breve de estado/error',
    HitoActual VARCHAR(50) NOT NULL DEFAULT 'APROBACION_PENDIENTE' COMMENT 'Hito actual persistido del onboarding',
    FechaCreacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FechaActualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FechaAprobacion DATETIME NULL,
    FechaEliminacion DATETIME NULL,
    UsuarioCreacion VARCHAR(100) NULL,
    UsuarioAprobacion VARCHAR(100) NULL,
    UsuarioEliminacion VARCHAR(100) NULL,
    MotivoEliminacion TEXT NULL,
    RazonSocial VARCHAR(150) NOT NULL,
    NombreFantasia VARCHAR(70) NULL,
    Domicilio VARCHAR(100) NOT NULL,
    EmailPrincipal VARCHAR(100) NOT NULL,
    Rut VARCHAR(20) NOT NULL,
    Telefono VARCHAR(30) NULL,
    Ciudad VARCHAR(100) NULL,
    Departamento VARCHAR(100) NULL,
    UsuarioEF VARCHAR(50) NOT NULL,
    ClaveUsuarioEF VARCHAR(100) NOT NULL,
    Licencia SMALLINT NULL,
    LicenciaTexto VARCHAR(150) NULL,
    Plan VARCHAR(200) NULL,
    Usuarios INT NULL DEFAULT 1,
    CfeMensuales INT NULL,
    ClienteIdGiro INT NOT NULL DEFAULT 0,
    ClienteIdVendedor VARCHAR(255) NOT NULL DEFAULT 'admin',
    ClienteIdFidelizacion INT NOT NULL DEFAULT 0,
    EmailEnvioFE VARCHAR(200) NULL,
    ClienteAbonado VARCHAR(2) NOT NULL DEFAULT 'NO',
    ClienteAbonadoIdProducto INT NOT NULL DEFAULT 0,
    ClienteAbonadoImporte DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ClienteAbonadoTV VARCHAR(10) NOT NULL DEFAULT 'CONTADO',
    ClienteAbonadoMoneda VARCHAR(3) NOT NULL DEFAULT 'UYU',
    ClienteAbonadoPeriodo VARCHAR(10) NOT NULL DEFAULT 'MENSUAL',
    ClienteAbonadoGrupo VARCHAR(20) NULL,
    ClienteAbonadoDescuento DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    ClientePnCreditoFiscal VARCHAR(2) NOT NULL DEFAULT 'NO',
    ClientePnMonto DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ClienteIdFormaPago INT NOT NULL DEFAULT 0,
    ClienteIdMedioPago INT NOT NULL DEFAULT 0,
    NombreCompletoFirmante VARCHAR(100) NULL,
    CIFirmante VARCHAR(20) NULL,
    ClienteAdenda VARCHAR(500) NULL,
    SucCodSucursal VARCHAR(20) NULL,
    SucCodFechaVigencia DATE NULL,
    AltaTipoEmpresa VARCHAR(20) NOT NULL DEFAULT 'SOCIEDAD',
    AltaEspecial VARCHAR(30) NOT NULL DEFAULT 'NO',
    AltaEspecialNorma VARCHAR(255) NULL,
    AltaEsEmisor VARCHAR(2) NOT NULL DEFAULT 'NO',
    AltaCreditoFiscal VARCHAR(30) NOT NULL DEFAULT 'NO',
    AltaCertificadoDigital VARCHAR(30) NULL,
    CarpetaBase VARCHAR(500) NULL,
    CarpetaCreada TINYINT(1) NOT NULL DEFAULT 0,
    Aprobada TINYINT(1) NOT NULL DEFAULT 0,
    EmpresaCreada TINYINT(1) NOT NULL DEFAULT 0,
    ClienteCreada TINYINT(1) NOT NULL DEFAULT 0,
    EmpresaIdCreada BIGINT UNSIGNED NULL,
    ClienteIdCreado INT NULL,
    Observaciones TEXT NULL,
    NotasAdmin TEXT NULL,
    ErrorProceso TEXT NULL,
    PRIMARY KEY (Id),
    KEY idx_En_Estado (Estado),
    KEY idx_En_Rut (Rut),
    KEY idx_En_RazonSocial (RazonSocial),
    KEY idx_En_FechaCreacion (FechaCreacion),
    KEY idx_En_EmpresaIdCreada (EmpresaIdCreada),
    KEY idx_En_ClienteIdCreado (ClienteIdCreado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS EmpresasNuevasArchivos (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NuevaEmpresaId BIGINT UNSIGNED NOT NULL,
    TipoArchivo VARCHAR(50) NOT NULL COMMENT 'pfx / credito_fiscal / contrato / f6906 / logo',
    NombreOriginal VARCHAR(255) NOT NULL,
    NombreGuardado VARCHAR(255) NOT NULL,
    RutaArchivo VARCHAR(500) NOT NULL COMMENT 'Guardar ruta relativa, no absoluta',
    Extension VARCHAR(20) NULL,
    MimeType VARCHAR(100) NULL,
    TamanoBytes BIGINT NULL,
    Obligatorio TINYINT(1) NOT NULL DEFAULT 0,
    Activo TINYINT(1) NOT NULL DEFAULT 1,
    FechaSubida DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UsuarioSubida VARCHAR(100) NULL,
    PRIMARY KEY (Id),
    KEY idx_Ena_NuevaEmpresaId (NuevaEmpresaId),
    KEY idx_Ena_TipoArchivo (TipoArchivo),
    CONSTRAINT fk_Ena_NuevaEmpresa
        FOREIGN KEY (NuevaEmpresaId)
        REFERENCES EmpresasNuevas(Id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS EmpresasNuevasHistorial (
    Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    NuevaEmpresaId BIGINT UNSIGNED NOT NULL,
    Evento VARCHAR(50) NOT NULL,
    EstadoAnterior VARCHAR(30) NULL,
    EstadoNuevo VARCHAR(30) NULL,
    Descripcion TEXT NULL,
    UsuarioEvento VARCHAR(100) NULL,
    FechaEvento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (Id),
    KEY idx_Enh_NuevaEmpresaId (NuevaEmpresaId),
    KEY idx_Enh_Evento (Evento),
    CONSTRAINT fk_Enh_NuevaEmpresa
        FOREIGN KEY (NuevaEmpresaId)
        REFERENCES EmpresasNuevas(Id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
