CREATE TABLE IF NOT EXISTS nuevas_empresas (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'PK del registro temporal',
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_APROBACION' COMMENT 'Estado actual del proceso',
    estado_detalle VARCHAR(255) NULL COMMENT 'Detalle breve de estado/error',
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    fecha_aprobacion DATETIME NULL,
    fecha_eliminacion DATETIME NULL,
    usuario_creacion VARCHAR(100) NULL,
    usuario_aprobacion VARCHAR(100) NULL,
    usuario_eliminacion VARCHAR(100) NULL,
    motivo_eliminacion TEXT NULL,
    razon_social VARCHAR(150) NOT NULL,
    nombre_fantasia VARCHAR(70) NULL,
    domicilio VARCHAR(100) NOT NULL,
    email_principal VARCHAR(100) NOT NULL,
    rut VARCHAR(20) NOT NULL,
    telefono VARCHAR(30) NULL,
    ciudad VARCHAR(100) NULL,
    departamento VARCHAR(100) NULL,
    usuario_ef VARCHAR(50) NOT NULL,
    clave_usuario_ef VARCHAR(100) NOT NULL,
    licencia SMALLINT NULL,
    licencia_texto VARCHAR(150) NULL,
    plan VARCHAR(200) NULL,
    usuarios INT NULL DEFAULT 1,
    cfe_mensuales INT NULL,
    cliente_id_giro INT NOT NULL DEFAULT 0,
    cliente_id_vendedor VARCHAR(255) NOT NULL DEFAULT 'admin',
    cliente_id_fidelizacion INT NOT NULL DEFAULT 0,
    email_envio_fe VARCHAR(200) NULL,
    cliente_abonado VARCHAR(2) NOT NULL DEFAULT 'NO',
    cliente_abonado_id_producto INT NOT NULL DEFAULT 0,
    cliente_abonado_importe DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cliente_abonado_tv VARCHAR(10) NOT NULL DEFAULT 'CONTADO',
    cliente_abonado_moneda VARCHAR(3) NOT NULL DEFAULT 'UYU',
    cliente_abonado_periodo VARCHAR(10) NOT NULL DEFAULT 'MENSUAL',
    cliente_abonado_grupo VARCHAR(20) NULL,
    cliente_abonado_descuento DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    cliente_pn_credito_fiscal VARCHAR(2) NOT NULL DEFAULT 'NO',
    cliente_pn_monto DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    cliente_id_formapago INT NOT NULL DEFAULT 0,
    cliente_id_medio_pago INT NOT NULL DEFAULT 0,
    nombre_completo_firmante VARCHAR(100) NULL,
    ci_firmante VARCHAR(20) NULL,
    cliente_adenda VARCHAR(500) NULL,
    suc_cod_sucursal VARCHAR(20) NULL,
    suc_cod_fecha_vigencia DATE NULL,
    alta_especial VARCHAR(30) NOT NULL DEFAULT 'NO',
    alta_especial_norma VARCHAR(255) NULL,
    alta_es_emisor VARCHAR(2) NOT NULL DEFAULT 'NO',
    alta_credito_fiscal VARCHAR(30) NOT NULL DEFAULT 'NO',
    alta_certificado_digital VARCHAR(30) NULL,
    carpeta_base VARCHAR(500) NULL,
    carpeta_creada TINYINT(1) NOT NULL DEFAULT 0,
    aprobada TINYINT(1) NOT NULL DEFAULT 0,
    empresa_creada TINYINT(1) NOT NULL DEFAULT 0,
    cliente_creado TINYINT(1) NOT NULL DEFAULT 0,
    empresa_id_creada BIGINT UNSIGNED NULL,
    cliente_id_creado INT NULL,
    observaciones TEXT NULL,
    notas_admin TEXT NULL,
    error_proceso TEXT NULL,
    PRIMARY KEY (id),
    KEY idx_ne_estado (estado),
    KEY idx_ne_rut (rut),
    KEY idx_ne_razon_social (razon_social),
    KEY idx_ne_fecha_creacion (fecha_creacion),
    KEY idx_ne_empresa_id_creada (empresa_id_creada),
    KEY idx_ne_cliente_id_creado (cliente_id_creado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nuevas_empresas_archivos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nueva_empresa_id BIGINT UNSIGNED NOT NULL,
    tipo_archivo VARCHAR(50) NOT NULL COMMENT 'pfx / credito_fiscal / contrato / f6906 / logo',
    nombre_original VARCHAR(255) NOT NULL,
    nombre_guardado VARCHAR(255) NOT NULL,
    ruta_archivo VARCHAR(500) NOT NULL COMMENT 'Guardar ruta relativa, no absoluta',
    extension VARCHAR(20) NULL,
    mime_type VARCHAR(100) NULL,
    tamano_bytes BIGINT NULL,
    obligatorio TINYINT(1) NOT NULL DEFAULT 0,
    activo TINYINT(1) NOT NULL DEFAULT 1,
    fecha_subida DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_subida VARCHAR(100) NULL,
    PRIMARY KEY (id),
    KEY idx_nea_nueva_empresa_id (nueva_empresa_id),
    KEY idx_nea_tipo_archivo (tipo_archivo),
    CONSTRAINT fk_nea_nueva_empresa
        FOREIGN KEY (nueva_empresa_id)
        REFERENCES nuevas_empresas(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS nuevas_empresas_historial (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nueva_empresa_id BIGINT UNSIGNED NOT NULL,
    evento VARCHAR(50) NOT NULL,
    estado_anterior VARCHAR(30) NULL,
    estado_nuevo VARCHAR(30) NULL,
    descripcion TEXT NULL,
    usuario_evento VARCHAR(100) NULL,
    fecha_evento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_neh_nueva_empresa_id (nueva_empresa_id),
    KEY idx_neh_evento (evento),
    CONSTRAINT fk_neh_nueva_empresa
        FOREIGN KEY (nueva_empresa_id)
        REFERENCES nuevas_empresas(id)
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
