ALTER TABLE EmpresasNuevas
    ADD COLUMN HitoActual VARCHAR(50) NOT NULL DEFAULT 'APROBACION_PENDIENTE'
    AFTER EstadoDetalle;

UPDATE EmpresasNuevas
SET HitoActual = CASE
    WHEN Estado = 'ELIMINADO' THEN 'CANCELADO'
    WHEN Estado = 'PENDIENTE_APROBACION' THEN 'APROBACION_PENDIENTE'
    WHEN Estado = 'ERROR_APROBACION' THEN 'ERROR_APROBACION'
    WHEN Estado = 'APROBADO' THEN 'EN_PROCESO'
    ELSE 'APROBACION_PENDIENTE'
END
WHERE HitoActual IS NULL OR TRIM(HitoActual) = '';
