CREATE TABLE IF NOT EXISTS `CertificadosNotificaciones` (
  `Id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `EmpresaId` INT NOT NULL,
  `Rut` VARCHAR(20) NOT NULL DEFAULT '',
  `RazonSocial` VARCHAR(255) NOT NULL DEFAULT '',
  `Apodo` VARCHAR(120) NOT NULL DEFAULT '',
  `CerStatus` VARCHAR(5) NOT NULL DEFAULT '',
  `DiasObjetivo` SMALLINT NOT NULL DEFAULT 0,
  `DiasRestantes` SMALLINT NOT NULL DEFAULT 0,
  `FechaVencimiento` DATE NOT NULL,
  `TipoNotificacion` VARCHAR(40) NOT NULL DEFAULT 'CERTIFICADO_VENCIMIENTO',
  `Destinatarios` TEXT NULL,
  `Copias` TEXT NULL,
  `Asunto` VARCHAR(255) NOT NULL DEFAULT '',
  `Plantilla` VARCHAR(150) NOT NULL DEFAULT '',
  `Estado` VARCHAR(20) NOT NULL DEFAULT 'ENVIADO',
  `Detalle` TEXT NULL,
  `BodyHtml` MEDIUMTEXT NULL,
  `PayloadJson` LONGTEXT NULL,
  `FechaEnvio` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CreatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UpdatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `idx_cert_notif_empresa_fecha` (`EmpresaId`, `FechaVencimiento`, `DiasObjetivo`),
  KEY `idx_cert_notif_rut_fecha` (`Rut`, `FechaVencimiento`),
  KEY `idx_cert_notif_estado` (`Estado`, `FechaEnvio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
