CREATE TABLE `Empresas` (
  `IdEmpresa` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `ImagenLogo` mediumblob,
  `ImagenInformeODS` mediumblob,
  `NombreFantasia` varchar(70) DEFAULT NULL,
  `RazonSocial` varchar(150) DEFAULT NULL,
  `M` tinyint(4) DEFAULT NULL,
  `Domicilio` varchar(50) DEFAULT NULL,
  `SitioWeb` varchar(50) DEFAULT NULL,
  `Email` varchar(50) DEFAULT NULL,
  `Habilitada` varchar(2) DEFAULT NULL COMMENT 'SI o NO',
  `EmpresaInvoicy` int(11) DEFAULT NULL,
  `Clave` varchar(100) DEFAULT NULL,
  `Ciudad` varchar(30) DEFAULT NULL,
  `Departamento` varchar(20) DEFAULT NULL,
  `creada` tinyint(4) DEFAULT NULL,
  `pServicio` tinyint(4) DEFAULT NULL COMMENT '1=Factura servicios',
  `pNoResguardo` tinyint(4) DEFAULT NULL COMMENT '1=No muestra resguardo/Menu',
  `pNoAbonados` tinyint(4) DEFAULT NULL COMMENT '1=No muestra abonados',
  `pGestionAbonados` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=nada, 1=Activo.',
  `pNoVentas` tinyint(4) DEFAULT NULL COMMENT '1=No mostrar Ventas',
  `pNoStock` tinyint(4) DEFAULT NULL COMMENT '1=No Mostrar Stock',
  `pNoCompras` tinyint(4) DEFAULT NULL COMMENT '1=No mostrar Compras',
  `pNoCajayBancos` tinyint(4) DEFAULT NULL COMMENT '1=No Muestra Caja y Bancos',
  `pCheques` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0 =No habilita Cheques,  1 = Habilita cheques',
  `pAgenda` tinyint(4) DEFAULT '0' COMMENT '0=No, 1=Activa agenda',
  `pNoCrm` tinyint(4) DEFAULT NULL COMMENT '1=No muestra CRM',
  `pNoProduccion` tinyint(4) DEFAULT NULL COMMENT '11=No Muestra Produccion',
  `pNoOpticas` tinyint(4) DEFAULT NULL COMMENT '1=No muestra Ppticas',
  `pNoVeterinarias` tinyint(4) DEFAULT NULL COMMENT '1=No muestra Veterinarias',
  `pImportaciones` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1 Habilita Importaciones',
  `pGestionPedidosClientes` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1 Habilita Gestion pedidos',
  `pFactMasivaExcel` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1 Habilita Fact Masiva',
  `pAsu` tinyint(4) DEFAULT NULL COMMENT '1=funcionalidad Asu',
  `pLec_Shopping` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0 = NO  1= SI, TIENE FUNCIONES DE SHOPPING',
  `pFacturador` tinyint(4) DEFAULT NULL COMMENT '0=650/1=Paquetes',
  `pFacturadorSoft` tinyint(4) NOT NULL COMMENT '0=nada 1=Acceso  Facturador',
  `pNotificaciones` tinyint(4) DEFAULT '0' COMMENT '0 = NO, 1 = Habilitado',
  `pTpvSoft` tinyint(4) NOT NULL COMMENT '0=Nada 1=Acceso TPV',
  `pSupervisorTPV` tinyint(4) DEFAULT NULL COMMENT '0=nada, 1 Pide autorización',
  `ClaveSupervisor` bigint(20) DEFAULT NULL,
  `pAvisarStock` tinyint(4) DEFAULT NULL COMMENT '1=avisa stock insuficiente',
  `pBalanza` tinyint(4) DEFAULT NULL COMMENT '0 = Precio, 1 = Peso',
  `pMediosDePago` int(11) NOT NULL DEFAULT '0',
  `pSucursales` tinyint(4) NOT NULL DEFAULT '0',
  `pCodBarra` varchar(2) NOT NULL DEFAULT 'NO',
  `pAgencia` tinyint(4) NOT NULL DEFAULT '0' COMMENT '1=RED PAGOS - 2 ABITAB',
  `pCodEmpresa` varchar(2) DEFAULT NULL,
  `pDescuentoItem` tinyint(4) NOT NULL DEFAULT '0' COMMENT '0=% 1=importe',
  `pPedProvee` tinyint(4) DEFAULT NULL COMMENT '1=Activa Pedidos Proveedores',
  `pRecibosElect` tinyint(4) DEFAULT '0' COMMENT '1 = Habilita función de Recibos Electrónicos en el sistema',
  `pContabilidad` tinyint(4) DEFAULT NULL COMMENT '0=Nada, 1 Integración, 2 Contabilidad.',
  `pMasDeUnTipoCae` tinyint(4) DEFAULT '0' COMMENT '0= normal, 1= Usa normal y Literal E',
  `pDescuentoMaximo` smallint(6) DEFAULT NULL COMMENT 'Descuento Maximo en %',
  `Usuarios` int(11) DEFAULT NULL,
  `PP` tinyint(4) DEFAULT NULL COMMENT '0=PRUEBAS/1=PRODUCCION',
  `Plan` varchar(200) DEFAULT NULL,
  `cProceso` varchar(30) DEFAULT NULL,
  `cSubProceso` varchar(100) DEFAULT NULL,
  `cUsuarioEmailInv` varchar(100) DEFAULT NULL,
  `cPassInv` varchar(100) DEFAULT NULL,
  `cPrioridad` varchar(5) DEFAULT NULL,
  `UltimoDiaDgi` date DEFAULT NULL,
  `FirmaDigital` varchar(100) DEFAULT NULL,
  `EnvioUyP` tinyint(4) DEFAULT NULL COMMENT 'Envío por email usuario y pass, 1 = SI',
  `PreF` tinyint(4) DEFAULT NULL COMMENT 'Prefinalizado. Falta solo el último paso , 1 = SI',
  `Rut` varchar(20) DEFAULT NULL,
  `UsuarioEF` varchar(20) DEFAULT NULL,
  `ClaveUsuarioEF` varchar(40) DEFAULT NULL,
  `Licencia` smallint(6) DEFAULT NULL,
  `IdUsuarioAD` varchar(255) DEFAULT NULL COMMENT 'Id Usuario Administrador de sistema',
  `Notas` varchar(4096) DEFAULT NULL COMMENT 'Notas de Certificacion de empresa',
  `Tilde` tinyint(4) DEFAULT NULL COMMENT 'Para hacer un tilde y trabajar con ese registro.',
  `PostularEn` date DEFAULT NULL COMMENT 'Fecha efectiva de postulación.',
  `FechaIP` date DEFAULT NULL,
  `bd` tinyint(4) DEFAULT '0' COMMENT '0=base de datos dynamica, 1 = base de datos independiente',
  `Notificar` tinyint(4) NOT NULL DEFAULT '2' COMMENT 'Notifica con 2 facturas en adelante, si es cero, No Notifica.',
  `NotificarSuspension` tinyint(4) NOT NULL DEFAULT '3',
  `Suspension` tinyint(4) NOT NULL DEFAULT '4',
  `LiteralE` tinyint(4) DEFAULT '0' COMMENT '0 Normal, 1 Literal E, Monotributo, otros',
  `Sms_Gratuitos` smallint(6) DEFAULT '100',
  `Sms_Comprados` mediumint(9) DEFAULT '0',
  `EmailUsuario` varchar(250) DEFAULT NULL,
  `EmailPass` varchar(250) DEFAULT NULL,
  `EmailEmail` varchar(250) DEFAULT NULL,
  `EmailPuerto` int(11) DEFAULT NULL,
  `EmailConexion` varchar(1) DEFAULT NULL,
  `Servidor` varchar(250) DEFAULT NULL,
  `Lec_Usuario` varchar(40) DEFAULT NULL,
  `Lec_Pass` varchar(40) DEFAULT NULL,
  `Coneccion` varchar(20) DEFAULT '' COMMENT 'Conección a BD independiente.',
  `Shopify` set('DESACTIVADO','ACTIVADO','PRUEBAS') NOT NULL DEFAULT 'DESACTIVADO' COMMENT 'Para activar, desactivar, poner en modo pruebas para que envíe dos documentos a la empresa admin de producción la integración con Shopify, hay que tener en cuenta que el desarrollo no está en el ámbito de desarrollo sino en producción y que para activarlo a otras empresas tocaría duplicar la carpeta /var/www/shopify  y llamarla con el nombre identificación de la empresa o algo así por el estilo para que se diferencien. Ejemplo shopify_idcliente (o el nombre)',
  `IdMedioPagoSistarbanc` int(11) NOT NULL DEFAULT '0' COMMENT 'Medio de pago usado para cuando se reciben pagos por Sistarbanc',
  UNIQUE KEY `IdEmpresa` (`IdEmpresa`),
  KEY `porConsumo` (`Habilitada`,`IdEmpresa`,`RazonSocial`,`Rut`)
) ENGINE=InnoDB AUTO_INCREMENT=1186 DEFAULT CHARSET=latin1
